version: 0.2

# BuildSpec for Users Microservice
# This file defines the build process for creating and pushing Docker images to ECR
# Includes testing, linting, and security scanning

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${IMAGE_TAG:-latest}
      - echo Repository URI is $REPOSITORY_URI
      - echo Image tag is $IMAGE_TAG
      - cd users
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Build started on `date`
      
      # Run linting
      - echo Running ESLint...
      - npm run lint
      
      # Run tests with coverage
      - echo Running tests with coverage...
      - npm test
      
      # Security scanning with npm audit
      - echo Running security audit...
      - npm audit --audit-level=moderate || true
      
      # Build Docker image
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$COMMIT_HASH
      
      # Scan Docker image for vulnerabilities
      - echo Scanning Docker image...
      - |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:latest image --severity HIGH,CRITICAL \
          --exit-code 0 $IMAGE_REPO_NAME:$IMAGE_TAG || true

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > ../imagedefinitions.json
      - cat ../imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  name: BuildArtifact

reports:
  test_report:
    files:
      - 'users/coverage/lcov.info'
    file-format: 'CLOVERXML'
  coverage_report:
    files:
      - 'users/coverage/clover.xml'
    file-format: 'CLOVERXML'

cache:
  paths:
    - '/root/.npm/**/*'
